# -*- coding: utf-8 -*-
"""grievance_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljbnejlA95kCCVAbtE3nu55__zS55FLU
"""

import torch
torch.cuda.is_available()

!pip install transformers datasets scikit-learn accelerate -q

import pandas as pd

df = pd.read_csv("/content/grievance_dataset_full.csv")
df.head()

label_encoder = LabelEncoder()
df["label"] = label_encoder.fit_transform(df["category"])

num_labels = df["label"].nunique()
print("Number of labels:", num_labels)

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["label"],
    random_state=42
)

model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

def tokenize_function(example):
    return tokenizer(
        example["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

!pip install --upgrade transformers -q

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels
)

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "f1": f1_score(labels, predictions, average="weighted")
    }

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",      # <-- correct for v5
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    load_best_model_at_end=True,
    report_to="none"
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.evaluate()

model.save_pretrained("grievance_model")
tokenizer.save_pretrained("grievance_model")

!zip -r grievance_model.zip grievance_model

